### ISSUE TITLE
找不到模块profiler.node' 

### ISSUE THREAD

**Issue by chong0808** [hyj1991/easy-monitor#64]
node -v 
v8.9.0
os version  windows 7

```
Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v5.7.7/node-v57-win32-x64/profiler.node'
redis is connected
redis 3 is connected
redis4 is connected
MongoClient is connected
rabbitMq is connected
[Easy-Monitor] <common.profiler.js> load error: Error: Cannot find module './build/profiler/v5.7.7/node-v57-win32-x64/profiler.node'
[Easy-Monitor: dashboard <9840>] http_server start at 12333...
[Easy-Monitor: dashboard <9840>] tcp_server start at 26666...
[Easy-Monitor: embrace <16264>] connect to 127.0.0.1:26666 success...
[Easy-Monitor: dashboard <9840>] tcp_client socket closed, info is undefined
[Easy-Monitor: dashboard <9840>] tcp_client socket closed, info is undefined
[Easy-Monitor: dashboard <9840>] tcp_client socket closed, info is undefined
[Easy-Monitor: dashboard <9840>] tcp_client socket closed, info is undefined
[Easy-Monitor: dashboard <9840>] tcp_client socket closed, info is undefined
[Easy-Monitor: dashboard <9840>] tcp_client socket closed, info is undefined
[Easy-Monitor: dashboard <9840>] tcp_client socket closed, info is undefined
[Easy-Monitor: dashboard <9840>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined[Easy-Monitor: embrace <16264>] common.socket->onData error: TypeError: Cannot read property 'profilerP' of undefined
    at _start (F:\SVN\xxxx\zc\share.schedule\node_modules\easy-monitor\src_logic\embrace\controller\tcp.profiler.js:48:52)
    at _start.next (<anonymous>)
    at onFulfilled (F:\SVNxxxx\zc\share.schedule\node_modules\co\index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[Easy-Monitor: dashboard <9840>] common.socket->onData error: TypeError: Cannot read property 'composeKey' of undefined
    at _stat (F:\SVN\xxxx\zc\share.schedule\node_modules\easy-monitor\src_logic\dashboard\controller\tcp\tcp.stat.js:34:41)
    at _stat.next (<anonymous>)
    at onFulfilled (F:\SVN\xxxx\zc\share.schedule\node_modules\co\index.js:65:19)
    at F:\SVN\xxxx\zc\share.schedule\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (F:\SVN\xxxx\zc\share.schedule\node_modules\co\index.js:50:10)
    at controller.(anonymous function) (F:\SVN\xxxx\zc\share.schedule\node_modules\easy-monitor\src_logic\dashboard\controller\tcp\tcp.stat.js:20:16)
    at tmpArr.forEach.item (F:\SVN\xxxx\zc\share.schedule\node_modules\easy-monitor\src_logic\common\common.socket.js:102:67)
    at Array.forEach (<anonymous>)
    at Object.onData (F:\SVN\xxxx\zc\share.schedule\node_modules\easy-monitor\src_logic\common\common.socket.js:93:20)
[Easy-Monitor: dashboard <9840>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <9840>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <9840>] http.axios.detail error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <9840>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <9840>] http.axios.detail error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <9840>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined
[Easy-Monitor: dashboard <9840>] http.axios.profiler error: TypeError: Cannot read property 'composeKey' of undefined

`````

**Comment by hyj1991** [comment]
看起来是 v8-profiler-node8 这个包没有安装成功
你手动安装下看看：

```bash
npm install v8-profiler-node8
```

**Comment by chong0808** [comment]
安装了还是报这个
但是刚看安装的过程发现这样 是没有安装 成功吗
刚试了npm  不行 
然后就改用cnpm  还是不行  
```
cnpm install v8-profiler-node8
√ Installed 1 packages
√ Linked 108 latest versions
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.7 and node@8.9.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz

F:\SVNxxxxx\zc\share.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8>node "C:\Users\zhengchong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" clean

F:\SVN\xxxx\zc\share.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8>node "C:\Users\zhengchong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" configure --fallback-to-build
--module=F:\SVN\xxxxx\zc\share.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8\build\profiler\v5.7.7\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=F:\SVN\xxxx\zc\share.schedule\node_modul
es\_v8-profiler-node8@5.7.7@v8-profiler-node8\build\profiler\v5.7.7\node-v57-win32-x64

F:\SVN\xxxxx\zc\share.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8>node "C:\Users\zhengchong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" build --fallback-to-build --mo
dule=F:\SVN\xxxx\zc\share.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8\build\profiler\v5.7.7\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=F:\SVN\xxxx\zc\share.schedule\node_modules\_
v8-profiler-node8@5.7.7@v8-profiler-node8\build\profiler\v5.7.7\node-v57-win32-x64
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  profiler.cc
  cpu_profiler.cc
  cpu_profile.cc
  cpu_profile_node.cc
f:\svn\即时通讯\zc\share.schedule\node_modules\_nan@2.10.0@nan\nan_new.h(208): warning C4244: 'argument': conversion from 'int64_t' to 'double', possible loss of data (compiling source file ..\src\cpu_profile.cc) [F:\SVN\xxx\zc\sh
are.sch
edule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8\build\profiler.vcxproj]
  ..\src\cpu_profile.cc(82): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number,int64_t>(A0)' being compiled
          with
          [
              A0=int64_t
          ] (compiling source file ..\src\cpu_profile.cc)
  heap_profiler.cc
  heap_snapshot.cc
  heap_output_stream.cc
..\src\heap_snapshot.cc(101): warning C4244: 'argument': conversion from 'int64_t' to 'uint32_t', possible loss of data (compiling source file ..\src\heap_snapshot.cc) [F:\SVN\xxx\zc\share.schedule\node_modules\_v8-profiler-node8@
5.7
.7@v8-profiler-node8\build\profiler.vcxproj]
  heap_graph_node.cc
..\src\heap_graph_node.cc(69): warning C4996: 'v8::Object::Has': was declared deprecated (compiling source file ..\src\heap_graph_node.cc) [F:\SVN\xxxx\zc\share.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8\build
\pr
ofiler.vcxproj]
  c:\users\zhengchong\.node-gyp\8.9.0\include\node\v8.h(3156): note: see declaration of 'v8::Object::Has' (compiling source file ..\src\heap_graph_node.cc)
f:\svn\xxxx\zc\share.schedule\node_modules\_nan@2.10.0@nan\nan_new.h(208): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of data (compiling source file ..\src\heap_graph_node.cc) [F:\SVN\xxx\zc\s
hare.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8\build\profiler.vcxproj]
  ..\src\heap_graph_node.cc(126): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number,std::size_t>(std::A0)' being compiled
          with
          [
              A0=std::size_t
          ] (compiling source file ..\src\heap_graph_node.cc)
  heap_graph_edge.cc
     Creating library F:\SVN\xxxx\zc\share.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8\build\Release\profiler.lib and object F:\SVN\xxxx\zc\share.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-n
ode8\bu
  ild\Release\profiler.exp
  Generating code
  Finished generating code
  profiler.vcxproj -> F:\SVN\xxx\zc\share.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8\build\Release\\profiler.node
  profiler.vcxproj -> F:\SVN\xxxx\zc\share.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8\build\Release\profiler.pdb (Full PDB)
  Copying F:\SVN\xxx\zc\share.schedule\node_modules\_v8-profiler-node8@5.7.7@v8-profiler-node8\build\Release\/profiler.node to F:/SVN/??3???é??è?ˉ/zc/share.schedule/node_modules/_v8-profiler-node8@5.7.7@v8-profiler-node8/build/pr
ofil
  er/v5.7.7/node-v57-win32-x64\profiler.node
  文件名、目录名或卷标语法不正确。
  已复制         0 个文件。
√ Run 1 scripts
Recently updated (since 2018-04-02): 2 packages (detail see file F:\SVN\xx\zc\share.schedule\node_modules\.recently_updates.txt)
√ All packages installed (112 packages installed from npm registry, used 56s, speed 12.37kB/s, json 109(284.19kB), tarball 412.82kB)
```
看错误有个这么一行 
````
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.7 and node@8.9.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
```
下载不了吗··

**Comment by hyj1991** [comment]
和下载没关系，本来就没有 v57 编译好的 binary，就是要 404 后走本地 node-gyp 编译的，你按我说的手动安装下 v8-profiler-node8 这个包看看有没有错误信息

**Comment by chong0808** [comment]
刚上面的就是手动安装的，如果那个404是正常的话 那就没有报错了。。。
按照这个issue [#53](https://github.com/hyj1991/easy-monitor/issues/53) 看  node-gyp 环境变量正常 

> 你要不试下 npm install v8-profiler 或者 npm install v8-profiler-next 这个两个包看看能不能成功，win 下安装扩展是会出现各种奇怪的问题...

安装 npm install v8-profiler这个也是成功的

**Comment by hyj1991** [comment]
@chong0808 那确实安装成功了，只是 copy 到 build/profiler/v5.7.7/node-v57-win32-x64/ 下的时候失败了，你看下是不是目录嵌套太深了。。。我记得 win 下目录太深后无法创建目录

**Comment by chong0808** [comment]
build/profiler/v5.7.7/node-v57-win32-x64/   这个文件目录是哪里的？
我手动把这个 profiler.node 复制到这里 build/profiler/v5.7.7/node-v57-win32-x64/ 下面可以吗？？

**Comment by hyj1991** [comment]
@chong0808 就是上面的

```bash
node_modules/v8-profiler-node8/build/profiler/v5.7.7/node-v57-win32-x64/
```

这个目录，你可以试下手动创建这个目录并且把 **profiler.node** 复制过去，可能也会失败，估计就是和 win 的文件目录路径深度有关系

**Comment by chong0808** [comment]
果然还是失败了 
windows 坑初尝试
