### ISSUE TITLE
macos安装的时候，报v8-profiler-node8@5.7.8编译错误

### ISSUE THREAD

**Issue by qinyang912** [hyj1991/easy-monitor#81]
v8-profiler-node8好像已经更新到了6.0.1，我直接安装6.0.1不会报错，但安装5.7.8就会报错

npm: 4.5.0
node: 10.5.0

```shell
> v8-profiler-node8@5.7.8 install /Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.5.0 | darwin | x64
node-pre-gyp info check checked for "/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64/profiler.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@10.5.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.8 and node@10.5.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
gypgyp info  it worked if it ends with ok
info it worked if it ends with ok
gypgyp info using node-gyp@3.8.0
 gypinfo info  usingusing node@10.5.0 | darwin | x64
 node-gyp@3.8.0
gyp info using node@10.5.0 | darwin | x64
gypgyp info ok
 info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.5.0 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.5.0 | darwin | x64
gypgyp  info spawn /usr/bin/python
info spawn /usr/bin/python
gyp info spawn args [ '/Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp/gyp/gyp_main.py',
gyp infogyp  spawn argsinfo   'binding.gyp',
 gypspawn args  [ '/Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp/gyp/gyp_main.py',
infogyp  spawn argsinfo   '-f',
 gypspawn args    'binding.gyp',
infogyp  spawn args   'make',
info gypspawn args    '-f',
info gypspawn args    '-I',
info gypspawn args    'make',
info gypspawn args    '/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8/build/config.gypi',
info gypspawn args    '-I',
info spawn args   '-I',
gyp info spawn args   '/Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/qinyang/.node-gyp/10.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/qinyang/.node-gyp/10.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/qinyang/.node-gyp/10.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gypgyp info spawn args   '/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp/addon.gypi',
gyp info  spawn args   '-I',
infogyp  spawn argsinfo   '-Goutput_dir=.' ]
 spawn args   '/Users/qinyang/.node-gyp/10.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/qinyang/.node-gyp/10.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/qinyang/.node-gyp/10.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.5.0 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.5.0 | darwin | x64
gypgyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
 info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/profiler.o
rm: ./Release/.deps/Release/obj.target/profiler/src/profiler.o.d.raw: No such file or directory
make: *** [Release/obj.target/profiler/src/profiler.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64"
gyp ERR! cwd /Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8
gyp ERR! node -v v10.5.0
gyp   CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64/profiler.node --module_name=profiler --module_path=/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8
node-pre-gyp ERR! node -v v10.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64/profiler.node --module_name=profiler --module_path=/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64' (1)
npm info lifecycle v8-profiler-node8@5.7.8~install: Failed to exec install script
- chownr@1.0.1 node_modules/chownr
- ignore-walk@3.0.1 node_modules/ignore-walk
- yallist@3.0.2 node_modules/minipass/node_modules/yallist
- minipass@2.3.4 node_modules/minipass
- fs-minipass@1.2.5 node_modules/fs-minipass
- minizlib@1.1.0 node_modules/minizlib
- needle@2.2.3 node_modules/needle
- npm-bundled@1.0.5 node_modules/npm-bundled
- npm-packlist@1.1.11 node_modules/npm-packlist
debug@2.6.9 node_modules/needle/node_modules/debug -> node_modules/tar-pack/node_modules/debug
- yallist@3.0.2 node_modules/tar/node_modules/yallist
npm WARN reditor-server@0.0.1 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-profiler-node8 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-profiler-node8
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-profiler-node8
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qinyang/.npm/_logs/2018-09-11T01_59_26_168Z-debug.log
../src/cpu_profiler.cc:2:10: fatal error: 'cpu_profile.h' file not
      found
#include "cpu_profile.h"
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/profiler/src/cpu_profiler.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/Volumes/Transcend/rishiqing/rishiqing-editor/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v64-darwin-x64"
gyp ERR! cwd /Volumes/Transcend/rishiqing/rishiqing-editor/server/node_modules/v8-profiler-node8
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by hyj1991** [comment]
因为你的 node 升级了啊，所以才更新了 v8-profiler-node8 的版本
貌似忘了把 easy-monitor 的依赖升级了，你来提个 pr 修改下版本号？

**Comment by hyj1991** [comment]
👌

**Comment by hyj1991** [comment]
easy-monitor@2.2.4 已经发布
